### PR TITLE
Seperated name from card

### PR DESCRIPTION
**Pull request by MrinalVarshney**
## Description

**Seperated title from image card**

## Related Issue

- **Some styling including animations for name in index.css**
- **Rearrangement  of components of Title card in  index.js** 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots (if appropriate):
[screen-capture (1).webm](https://github.com/ContriHUB/Jodi-Makers/assets/66404121/f0d263ae-4088-49d2-b8ed-7319dac81897)

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by admirerr** [comment]
@MrinalVarshney You have changed the start script code from 'start:frontend' to 'start'. Revert it back to its previous stage.

**Comment by MrinalVarshney** [comment]
Done sir !

**Comment by priyanshagra** [comment]
this issue is assigned to me i thought

**Comment by MrinalVarshney** [comment]
> this issue is assigned to me i 
  It's being assigned to me earlier...

**Review by admirerr — APPROVED** [review]

**Pull request merged**
