### PR TITLE
added glassmorphism effect to signup /create account

### PR DESCRIPTION
**Pull request by priyanshagra**
added glassmorphism effect to signup /create account to  automodel.js

## Description
->Fisrtly setup the project locally
->in first page fixed the css so that signin and create account to have glassmorphism effect
->basicly created  a constant of glassmorphism effect having important css of backdropFilter: 'blur(10px)', 
  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' 
->apply this css to div enclosing whole code
-> you can opacity accordingly

Fixes # (issue) added glassmorphism effect to signup /create account

## Type of change CSS based

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] This change requires a documentation update

## Motivation and Context
This will attract user towrds it

## How Has This Been Tested?
By seeing preview

## Screenshots (if appropriate):
Screenshot 2023-10-10 025825
Screenshot 2023-10-10 025845

## Checklist:

- [x ] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [ x] My code follows the code style of this project.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] Any dependent changes have been merged and published in downstream modules
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by admirerr** [comment]
> added glassmorphism effect to signup /create account to automodel.js
> 
> ## Description
> ->Fisrtly setup the project locally ->in first page fixed the css so that signin and create account to have glassmorphism effect ->basicly created a constant of glassmorphism effect having important css of backdropFilter: 'blur(10px)', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' ->apply this css to div enclosing whole code -> you can opacity accordingly
> 
> Fixes # (issue) added glassmorphism effect to signup /create account
> 
> ## Type of change CSS based
> * [ x] Bug fix (non-breaking change which fixes an issue)
> * [ x] New feature (non-breaking change which adds functionality)
> * [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [x ] This change requires a documentation update
> 
> ## Motivation and Context
> This will attract user towrds it
> 
> ## How Has This Been Tested?
> By seeing preview
> 
> ## Screenshots (if appropriate):
> Screenshot 2023-10-10 025825 Screenshot 2023-10-10 025845
> 
> ## Checklist:
> * [x ] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
> * [ x] My code follows the code style of this project.
> * [ x] I have commented my code, particularly in hard-to-understand areas
> * [ x] My changes generate no new warnings
> * [ x] My change requires a change to the documentation.
> * [ x] I have updated the documentation accordingly.
> * [ x] I have read the **CONTRIBUTING** document.
> * [ x] Any dependent changes have been merged and published in downstream modules
> * [ x] I have added tests to cover my changes.
> * [ x] All new and existing tests passed.
> 
> **Test Configuration**:
> 
> * Firmware version:
> * Hardware:
> * Toolchain:
> * SDK:

@priyanshagra You have overridden some of the previous merged PR. Resolve it and post an update here when you are done.

**Comment by priyanshagra** [comment]
Screenshot 2023-10-10 233544
Screenshot 2023-10-10 233532
taken code from main branch update in my pr

**Comment by admirerr** [comment]
@priyanshagra Continue with google button isn't functional. Work on making it functional as it was before.

**Comment by priyanshagra** [comment]
maked google button functional it was the mistake of previous merge that remove onclick event although fixed it
Screenshot 2023-10-11 222436

**Comment by priyanshagra** [comment]
done  please check

**Review by admirerr — APPROVED** [review]

**Comment by priyanshagra** [comment]
Awesome, thanks for the update!

**Pull request merged**
