### PR TITLE
Change bar color

### PR DESCRIPTION
**Pull request by Ishsinghal**
## Description

1. **Handling useState according to the buttons clicked.**
2. **Conditional rendering for settingup of styles**

## Related Issue

--**Currently when chat is selected, Match is not faded  and same for opposite.**

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots (if appropriate):
[screen-capture.webm](https://github.com/ContriHUB/Jodi-Makers/assets/125989792/687d12ca-9c06-4b6e-b430-2656285ccb10)
## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by admirerr** [comment]
@Ishsinghal When you switch mode between chat and matches the width of the sidebar is changing. Try to fix it out.

**Comment by Ishsinghal** [comment]
Done sir !
[screen-capture (1).webm](https://github.com/ContriHUB/Jodi-Makers/assets/125989792/fecbb6c8-2760-4df5-a171-9b8c5d75eac9)

**Comment by Ishsinghal** [comment]
Check sir, I did it..

**Review by admirerr — DISMISSED** [review]

**Comment by Ishsinghal** [comment]
Good morning sir, Actually sir you approved my changes but didn't merge
it.....

**Comment by shank03** [comment]
@Ishsinghal Here are few things you have to do
- Delete `node_modules` folder and `package-lock.json` from both `server` and `client` folder if exsits and commit.
- Update `.gitignore` to ignore `nodes_modules` folder and `package-lock.json` file and commit.

Push these commits

**Pull request merged**
