### PR TITLE
Change the name in the logo

### PR DESCRIPTION
**Pull request by akshatvermavi**
Throughout all the pages wherever you find the name tinder replace it with the name Jodi-Makers is now done. Now owners and users can enjoy with new logo of Jodi-Makers
Jodi-Makers

### CODE REVIEW

**Comment by admirerr** [comment]
> Throughout all the pages wherever you find the name tinder replace it with the name Jodi-Makers is now done. Now owners and users can enjoy with new logo of Jodi-Makers Jodi-Makers

Screenshot 2023-10-12 at 11 53 56 AM

@akshatvermavi  Make the logo transparent. Try to remove this black box.

**Comment by akshatvermavi** [comment]
Sir Now you can see the changes and suggest me if any changes are require
Jodi-Makers

**Comment by admirerr** [comment]
> Sir Now you can see the changes and suggest me if any changes are require Jodi-Makers

Try to remove these watermark and then integrate this image in the code.

**Comment by akshatvermavi** [comment]
[image: sodapdf-converted(1).png]
Hii sir sorry for the late reply now it ready so I am going to replace it

**Comment by akshatvermavi** [comment]
Sir now you can changes and approve my request
Branch Link <https://github.com/akshatvermavi/Jodi-Makers/tree/test2>

**Comment by admirerr** [comment]
@akshatvermavi Here are the few modifications that you are supposed to do

- Remove background of `Jodi-Makers.png` in `client/src/images` using some background remover tool and commit. Take care that image must not contain any watermark. 
- You have used the name `Jodi-Makers.jpg` in `client/src/components/Nav.js`. Update it to `Jodi-Makers.png` and commit.

Push these commits.

**Comment by akshatvermavi** [comment]
Sir, i made the required changes of file name in the path i.e.
Jodi-Makers.jpeg to Jodi-Makers.png
      So it's my humble request to you that please review my PR and merge
it.
Branch LINK <https://github.com/akshatvermavi/Jodi-Makers/tree/test2>

**Comment by admirerr** [comment]
> 4fb6282

@akshatvermavi You missed modification mentioned in `point 1` i.e.- (Removal of background of image using some background removal tool).

**Comment by akshatvermavi** [comment]
Sir The background is already removed, its white will work. I am attaching
the Image please comment it out.

**Review by admirerr — APPROVED** [review]

**Comment by admirerr** [comment]
@akshatvermavi Raise a PR approval request on ContriHUB website.

**Comment by akshatvermavi** [comment]
Thank You sir, please update in the contrihub website for main issue and
for some extra work for creation of logo also.

**Pull request merged**
