### PR TITLE
Added option to upload photo in onboarding.js

### PR DESCRIPTION
**Pull request by priyanshagra**
Added option to upload photo in onboarding.js

Description step by step:
->Basically after setting up project locally 
->connecting to my mongodb login
-> then got to page onboarding.js
-> then change the section of input image through url to desktop although donot change the name of input that is url
->sothat there might be any clashes in server to fetch the input image to store in database

Fixes # (issue)  Added option to upload photo in onboarding.js

## Type of change 

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## Motivation and Context

This saves the time of user and increase comfort in using the web  

## How Has This Been Tested?

 Tested multiple times
 please see screenshorts
 no effect in other area

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [ x] My code follows the code style of this project.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] Any dependent changes have been merged and published in downstream modules
- [ x] I have added tests to cover my changes.
- [ x]
Screenshot 2023-10-10 013714
Screenshot 2023-10-10 013736
Screenshot 2023-10-10 013757

All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by admirerr** [comment]
@priyanshagra Photo isn't being stored in the database. We are supposed to store image in the database and fetch it from there whenever required.

**Comment by priyanshagra** [comment]
done i fixed

**Comment by priyanshagra** [comment]
done sir added to store in database functionality in server

**Comment by admirerr** [comment]
Screenshot 2023-10-11 at 11 16 55 PM

@priyanshagra Only a predefined path is being stored in the database. It should store the content of the image.

**Comment by priyanshagra** [comment]
please install module multer and image file name is saved in database and image is saved in multer buffer and can be used through name please merge

**Comment by admirerr** [comment]
> please install module multer and image file name is saved in database and image is saved in multer buffer and can be used through name please merge

Add a line in the Readme file mentioning that you will be required to install multer to store image in its buffer.

**Comment by priyanshagra** [comment]
Done.

**Review by admirerr — APPROVED** [review]

**Pull request merged**
