### PR TITLE
feat: added google oauth

### LINKED ISSUE #7: Add Google Auth
Provide the option for SignIn/SignUp through Google Auth. User must land on to a new page where he must be required to fill additional details which is necessary for the account creation.

### PR DESCRIPTION
**Pull request by lokesh-wagh**
## Description
1. added a outhHandler component that can be called from backend to create cookie's
2. added a the neccessary endpoint's for google auth in index.js
3. added the button's and handler's that trigger google authentication

I have directed the user from frontend to backend using authgoogle endpoint
then the user is redirected to google consent screen 
after that success oauthloger is mounted in react that save's the cookies
then to further fill the required detail's user is redirected to onboarding

## Related Issue
fixes #7 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screens
[jodimaker bug.webm](https://github.com/ContriHUB/Jodi-Makers/assets/129964049/2a1c72d6-0578-40d8-a205-90eceb1697da)
hots (if appropriate):

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by lokesh-wagh** [comment]
Hey!!!
@admirerr 
Can you review this pr and tell me about the change's

**Comment by admirerr** [comment]
@lokesh-wagh keep the Google account permission enabled for all.

**Comment by admirerr** [comment]
> Hey!!! @admirerr Can you review this pr and tell me about the change's

@lokesh-wagh  keep the Google account permission enabled for all.

**Comment by lokesh-wagh** [comment]
I didn't get you 
can you elaborate

**Comment by admirerr** [comment]
> I didn't get you can you elaborate

Screenshot 2023-10-09 at 7 52 43 PM

I am asking you to resolve this issue.

**Comment by lokesh-wagh** [comment]
Screenshot 2023-10-09 200606
this screen will be opened on consenting 

go to advanced and proceed to jodimaker
because api is still under verification by google(this issue can be bypassed  by adding a email to test users)

then we can proceed normally

image


if i have missed something then please guide me

**Comment by lokesh-wagh** [comment]
image

image

**Review by admirerr — APPROVED** [review]

**Comment by lokesh-wagh** [comment]
Thank you for the guidance sir!!

**Pull request merged**
